### ISSUE TITLE
invalid character detected in xml from dahua camera  &#x0

### ISSUE THREAD

**Issue by marcbellocchio** [MarvinSmarDTV/Compare-XML-ONVIF-Test#5]
The input file shall be cleaned up beofre being processed by the tool.

import re

invalid_xml = re.compile(r'&#x[0-1]?[0-9a-eA-E];')

new_file = open('new_file.xml','w') 
with open('old_file.xml') as f:
    for line in f:
        nline, count = invalid_xml.subn('',line)
        new_file.write(nline) 
new_file.close()

**Comment by MarvinSmarDTV** [comment]
Done in #7
